name: C++ CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.1.0
        with:
          distribution: "adopt"
          java-version: "11"
      - run: sudo sysctl kernel.perf_event_paranoid=1
      - run: make
      #- run: make test
      - uses: actions/upload-artifact@v2
        with:
          path: build/
